image: node:18-buster

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/
    - vendor/

variables:
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
  # SSH_HOST: ec2-user@your-ec2-ip
  SSH_PORT: 22

.before_script:
  - apt-get update -y
  - apt-get install -y openssh-client rsync

# working
.build:
  stage: build
  script:
    - npm install
    - npm run build
    # - composer install --no-dev --optimize-autoloader
    # - composer install --no-dev
  artifacts:
    paths:
      - public/
      - vendor/
      - node_modules/

# working
install_composer:
  stage: build
  image: php:8.2-cli  # Use a PHP image with CLI
  script:
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - composer --version  # Verify installation
    # Now you can run composer commands
    - composer install

# Not working
.test:
  stage: test
  script:
    - php artisan test

ssh_deploy:
  stage: .pre
  image: alpine
  script:
    # Check if id address and port 22 is open on the server
    - nc -zv $REMOTE_DEPLOY_HOST $SSH_PORT
    # View the SSH_PRIVATE_KEY
    - echo $SSH_PRIVATE_KEY
    - cat $SSH_PRIVATE_KEY

.deploy:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
    - rsync -avz --exclude node_modules --exclude vendor --delete-after . $SSH_HOST:/var/www/laravel-app
    - ssh $SSH_HOST "cd /var/www/laravel-app && composer install --no-dev && npm install && npm run build && php artisan migrate --force && php artisan config:cache && php artisan route:cache"
